version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.1.8
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=1
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    networks:
      - zeebe_network
  monitor:
    container_name: zeebe_monitor
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.1
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    volumes:
      - ./simple-monitor-application.yaml:/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
